name: Atualizar Mega Sena

on:
  schedule:
    - cron: '0 9 * * 1,3,5'
  workflow_dispatch:

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v5

      - name: Instalar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Rodar script de atualização
        run: node atualizar.js

      - name: Salvar alterações
        run: |
          git config --global user.name "Robo Atualizador"
          git config --global user.email "robo@github.com"
          git add resultados.json
          git diff --cached --quiet || (git commit -m "Atualização automática Mega-Sena" && git push)